
services:

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MatAleNic
      MYSQL_USER: username
      MYSQL_PASSWORD: MatAleNic
      MYSQL_DATABASE: BOSTARTER
    command: ["--log_bin_trust_function_creators=1"] #serve per far andare i trigger
    ports:
      - "3307:3306"
    networks:
      - databases
  
   
  phpmyadmin:
     image: phpmyadmin:latest
     restart: always
     depends_on:
       - mysql
     environment:
       PMA_HOST: mysql
       PMA_PORT: 3306
       PMA_USER: username
       PMA_PASSWORD: MatAleNic
     ports:
       - "9876:80"
     networks:
       - databases

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: MatAleNic
    ports:
      - "27018:27017"
    networks:
      - databases

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: MatAleNic
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8081:8081"
    networks:
      - databases
  apache:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - mongodb
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/
    networks:
      - databases

networks:
  databases:
    driver: bridge